// Capabilities page: what the Readiness Pack does, which shipped assets do it,
// and the full asset inventory. Data comes from two files kept honest by
// scripts/check-catalog.mjs at build time:
//   src/data/assetCatalog.json  generated by the pack (tools/gen-asset-catalog.py)
//   src/data/capabilities.js    hand-authored capability -> assets map
import React, { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { LIVE_KIBANA_BASE } from '../data/liveLinks.js'
import catalog from '../data/assetCatalog.json'
import { CAPABILITIES } from '../data/capabilities.js'

const TYPE_LABEL = Object.fromEntries(catalog.types.map(t => [t.key, t.label]))
const TYPE_ORDER = Object.fromEntries(catalog.types.map((t, i) => [t.key, i]))
const ASSETS_BY_ID = catalog.assets.reduce((m, a) => {
  ;(m[a.id] ||= []).push(a)
  return m
}, {})
const DASHBOARDS = Object.fromEntries(catalog.assets.filter(a => a.type === 'dashboard').map(a => [a.id, a]))

function live(path) {
  return path ? `${LIVE_KIBANA_BASE}${path}` : null
}

function ExternalIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 16 16" fill="none" aria-hidden="true" className="shrink-0">
      <path d="M6.5 3.5H3.8A1.3 1.3 0 002.5 4.8v7.4a1.3 1.3 0 001.3 1.3h7.4a1.3 1.3 0 001.3-1.3V9.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" />
      <path d="M9.5 2.5h4v4M13.2 2.8L7.5 8.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function LiveLink({ path, label = 'Open in demo', small }) {
  const href = live(path)
  if (!href) return null
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className={`inline-flex items-center gap-1.5 rounded border border-accent-blue/50 bg-accent-blue/10 text-accent-blue hover:bg-accent-blue/20 transition-colors whitespace-nowrap ${small ? 'text-[11px] px-2 py-0.5' : 'text-sm px-3 py-1.5'}`}
      style={{ borderStyle: 'solid' }}
    >
      <ExternalIcon />
      {label}
    </a>
  )
}

// ── Screenshots ────────────────────────────────────────────────────────────────

function ShotGrid({ shots, onOpen }) {
  if (!shots.length) return null
  return (
    <div className="mt-5 grid grid-cols-2 sm:grid-cols-3 gap-3">
      {shots.map((id, i) => {
        const d = DASHBOARDS[id]
        return (
          <button
            key={id}
            type="button"
            onClick={() => onOpen(i)}
            className="group text-left rounded-lg border border-line/50 bg-ink-900/40 overflow-hidden hover:border-accent-teal/60 focus:outline-none focus:ring-2 focus:ring-accent-teal/60"
            style={{ borderStyle: 'solid' }}
            aria-label={`Enlarge screenshot: ${d?.name || id}`}
          >
            <img
              src={`/screenshots/thumbs/${id}.jpg`}
              alt={d?.name || id}
              loading="lazy"
              className="w-full aspect-[2/1] object-cover object-top group-hover:opacity-90"
            />
            <p className="px-2 py-1.5 text-[11px] text-text-muted leading-snug truncate">{d?.name || id}</p>
          </button>
        )
      })}
    </div>
  )
}

function ShotModal({ shots, index, onClose, onStep }) {
  useEffect(() => {
    const handler = (e) => {
      if (e.key === 'Escape') onClose()
      if (e.key === 'ArrowRight') onStep(1)
      if (e.key === 'ArrowLeft') onStep(-1)
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [onClose, onStep])
  const id = shots[index]
  const d = DASHBOARDS[id]
  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 sm:p-8" onClick={onClose} role="dialog" aria-modal="true" aria-label={d?.name || id}>
      <div className="absolute inset-0 bg-black/75 backdrop-blur-sm" />
      <div
        className="relative w-full max-w-6xl flex flex-col rounded-xl bg-ink-900 border border-line shadow-2xl overflow-hidden"
        style={{ maxHeight: '92vh', borderStyle: 'solid' }}
        onClick={e => e.stopPropagation()}
      >
        <div className="flex items-center gap-3 px-5 py-3 border-b border-line/60 shrink-0">
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-text-primary truncate">{d?.name || id}</p>
            <p className="text-[11px] text-text-muted truncate">{id} · demo cluster, captured {catalog.generated}</p>
          </div>
          <LiveLink path={d?.live_path} label="Open this dashboard" small />
          {shots.length > 1 && (
            <span className="text-[11px] text-text-muted whitespace-nowrap">{index + 1} / {shots.length}</span>
          )}
          <button onClick={onClose} className="p-1.5 rounded hover:bg-ink-700 text-text-muted hover:text-text-primary" aria-label="Close">
            <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M2.293 2.293a1 1 0 0 1 1.414 0L8 6.586l4.293-4.293a1 1 0 1 1 1.414 1.414L9.414 8l4.293 4.293a1 1 0 0 1-1.414 1.414L8 9.414l-4.293 4.293a1 1 0 0 1-1.414-1.414L6.586 8 2.293 3.707a1 1 0 0 1 0-1.414Z"/></svg>
          </button>
        </div>
        <div className="relative overflow-auto flex-1 bg-black/40">
          <img src={`/screenshots/${id}.png`} alt={d?.name || id} className="w-full h-auto" />
          {shots.length > 1 && (
            <>
              <button onClick={() => onStep(-1)} aria-label="Previous screenshot" className="absolute left-2 top-1/2 -translate-y-1/2 rounded-full bg-ink-900/80 border border-line px-3 py-2 text-text-primary hover:bg-ink-700" style={{ borderStyle: 'solid' }}>‹</button>
              <button onClick={() => onStep(1)} aria-label="Next screenshot" className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full bg-ink-900/80 border border-line px-3 py-2 text-text-primary hover:bg-ink-700" style={{ borderStyle: 'solid' }}>›</button>
            </>
          )}
        </div>
        {d?.description && (
          <p className="px-5 py-3 text-xs text-text-muted leading-relaxed border-t border-line/60 shrink-0">{d.description}</p>
        )}
      </div>
    </div>
  )
}

// ── Asset rows ─────────────────────────────────────────────────────────────────

const FACT_LABEL = {
  index_patterns: 'patterns', data_stream: 'data stream', composed_of: 'composed of', ilm_policy: 'ILM', priority: 'priority',
  processors: 'processors', processor_types: 'processor types',
  kind: 'kind', source: 'source', dest_index: 'dest', dest_pipeline: 'dest pipeline', frequency: 'every', group_by: 'group by', continuous: 'continuous',
  source_indices: 'source', match_field: 'match on', enrich_fields: 'serves',
  phases: 'phases', schedule: 'schedule', actions: 'actions', registered_inactive: 'ships inactive',
  repository: 'repository', indices: 'indices', retention: 'retention', cluster: 'cluster',
  detectors: 'detectors', groups: 'groups', datafeed_indices: 'datafeed',
  panels: 'panels', rule_type: 'type', severity: 'severity', risk_score: 'risk', ships_enabled: 'ships enabled', index: 'index', tags: 'tags', ml_job_ids: 'ML jobs',
  index_pattern: 'pattern', time_field: 'time field', queries: 'queries', tools: 'tools', labels: 'labels', tool_type: 'type', pattern: 'pattern',
  source_file: 'source file', triggers: 'triggers',
}
const FACT_SKIP = new Set(['tags', 'labels', 'processor_types', 'source_file'])

function factText(v) {
  if (Array.isArray(v)) {
    if (v.length && typeof v[0] === 'object') return v.map(x => `${(x.names || []).join(', ')}: ${(x.privileges || []).join(', ')}`).join(' · ')
    return v.join(', ')
  }
  if (typeof v === 'object') return Object.entries(v).map(([k, x]) => `${k} ${x}`).join(', ')
  if (typeof v === 'boolean') return v ? 'yes' : 'no'
  return String(v)
}

function Facts({ facts }) {
  const rows = Object.entries(facts || {}).filter(([k]) => !FACT_SKIP.has(k))
  if (!rows.length) return null
  return (
    <dl className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-text-muted">
      {rows.map(([k, v]) => (
        <div key={k} className="flex gap-1 min-w-0 max-w-full">
          <dt className="shrink-0 uppercase tracking-wide text-text-muted/70">{FACT_LABEL[k] || k}</dt>
          <dd className="font-mono break-all">{factText(v)}</dd>
        </div>
      ))}
    </dl>
  )
}

function Description({ text }) {
  const [open, setOpen] = useState(false)
  const long = text.length > 320
  return (
    <p className="mt-1 text-sm text-text-primary leading-relaxed">
      {long && !open ? text.slice(0, 300).replace(/\s+\S*$/, '') + '…' : text}
      {long && (
        <button type="button" onClick={() => setOpen(o => !o)} className="ml-2 text-xs text-accent-teal hover:underline">
          {open ? 'less' : 'more'}
        </button>
      )}
    </p>
  )
}

function AssetRow({ asset, showType }) {
  const named = asset.name && asset.name !== asset.id
  return (
    <li className="py-3 border-t border-line/40 first:border-t-0">
      <div className="flex items-start gap-3">
        <div className="flex-1 min-w-0">
          {showType && <p className="text-[10px] uppercase tracking-wider text-text-muted/70">{TYPE_LABEL[asset.type]}</p>}
          <p className="text-sm font-semibold text-text-primary break-words">{named ? asset.name : asset.id}</p>
          {named && <p className="text-[11px] font-mono text-text-muted break-all">{asset.id}</p>}
        </div>
        <div className="shrink-0 flex items-center gap-2">
          <span className={`text-[10px] px-1.5 py-0.5 rounded border ${asset.delivery === 'epr' ? 'text-accent-purple border-accent-purple/40 bg-accent-purple/10' : 'text-accent-gray border-accent-gray/40 bg-accent-gray/10'}`} style={{ borderStyle: 'solid' }} title={asset.delivery === 'epr' ? 'Installs from the Fleet package' : 'Applied by the bootstrap loader'}>
            {asset.delivery === 'epr' ? 'package' : 'bootstrap'}
          </span>
          <LiveLink path={asset.live_path} small />
        </div>
      </div>
      <div className="pl-3 border-l border-line/30" style={{ borderLeftStyle: 'solid' }}>
        <Description text={asset.description} />
        {asset.live_note && !asset.live_path && <p className="mt-1 text-[11px] text-text-muted/70 italic">{asset.live_note}</p>}
        <Facts facts={asset.facts} />
      </div>
    </li>
  )
}

function Collapsible({ summary, count, note, children, defaultOpen = false }) {
  return (
    <details className="group rounded-lg border border-line/60 bg-ink-900/40" style={{ borderStyle: 'solid' }} open={defaultOpen}>
      <summary className="cursor-pointer select-none list-none flex items-center gap-3 px-4 py-2.5 text-sm text-text-primary hover:bg-ink-700/40 rounded-lg">
        <svg width="10" height="10" viewBox="0 0 10 10" className="transition-transform group-open:rotate-90 text-text-muted" aria-hidden="true"><path d="M3 1l4 4-4 4" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg>
        <span className="font-medium">{summary}</span>
        {count != null && <span className="text-xs text-text-muted">{count}</span>}
        {note && <span className="ml-auto text-[11px] text-text-muted/70 hidden sm:inline">{note}</span>}
      </summary>
      <div className="px-4 pb-3">{children}</div>
    </details>
  )
}

// ── Capability article ─────────────────────────────────────────────────────────

function resolveAssets(ids) {
  const seen = new Set()
  const out = []
  for (const id of ids) {
    for (const a of ASSETS_BY_ID[id] || []) {
      const k = `${a.type}/${a.id}`
      if (seen.has(k)) continue
      seen.add(k)
      out.push(a)
    }
  }
  return out.sort((x, y) => TYPE_ORDER[x.type] - TYPE_ORDER[y.type] || x.id.localeCompare(y.id))
}

function CapabilityArticle({ cap, onOpenShot }) {
  const assets = useMemo(() => resolveAssets(cap.assets), [cap.assets])
  const byType = useMemo(() => {
    const m = new Map()
    for (const a of assets) {
      if (!m.has(a.type)) m.set(a.type, [])
      m.get(a.type).push(a)
    }
    return [...m.entries()]
  }, [assets])
  // Collapsed by default: title, references and the descriptive paragraphs
  // stay visible; the chevron opens what does the work, the screenshots and
  // the related-asset list. A deep link (#capability-id) opens its panel.
  const [open, setOpen] = useState(() => typeof window !== 'undefined' && window.location.hash === `#${cap.id}`)
  useEffect(() => {
    const onHash = () => { if (window.location.hash === `#${cap.id}`) setOpen(true) }
    window.addEventListener('hashchange', onHash)
    return () => window.removeEventListener('hashchange', onHash)
  }, [cap.id])
  const detailsId = `${cap.id}-details`
  return (
    <article id={cap.id} className="rounded-lg border border-line bg-ink-800 px-7 py-6 scroll-mt-24" style={{ borderStyle: 'solid' }}>
      <div className="flex items-start gap-3">
        <button
          type="button"
          onClick={() => setOpen(o => !o)}
          aria-expanded={open}
          aria-controls={detailsId}
          className="mt-1.5 shrink-0 rounded p-1 text-text-muted hover:text-text-primary hover:bg-ink-700/60 focus:outline-none focus:ring-2 focus:ring-accent-teal/60"
          aria-label={open ? `Collapse ${cap.title}` : `Expand ${cap.title}`}
        >
          <svg width="12" height="12" viewBox="0 0 10 10" className={`transition-transform ${open ? 'rotate-90' : ''}`} aria-hidden="true"><path d="M3 1l4 4-4 4" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg>
        </button>
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1">
            <h3 className="text-lg font-semibold text-text-primary">
              <button type="button" onClick={() => setOpen(o => !o)} aria-expanded={open} aria-controls={detailsId} className="text-left hover:text-accent-teal focus:outline-none focus:underline">{cap.title}</button>
            </h3>
            <div className="flex flex-wrap gap-1.5">
              {cap.lra.map(r => (
                <span key={r} className="text-[10px] font-bold text-accent-blue bg-accent-blue/10 border border-accent-blue/30 px-1.5 py-0.5 rounded whitespace-nowrap" style={{ borderStyle: 'solid' }}>{r}</span>
              ))}
            </div>
          </div>
          {cap.body.map((para, i) => (
            <p key={i} className="mt-3 text-sm text-text-primary leading-relaxed">{para}</p>
          ))}
          {open && (
            <div id={detailsId}>
              <p className="mt-3 text-sm text-text-muted leading-relaxed">
                <span className="font-semibold text-text-primary">What does the work. </span>{cap.contributes}
              </p>
              <ShotGrid shots={cap.shots} onOpen={i => onOpenShot(cap.shots, i)} />
              <div className="mt-5">
                <Collapsible summary="Related assets" count={assets.length} note="name, function, link into the demo cluster">
                  <div className="space-y-3 mt-1">
                    {byType.map(([type, list]) => (
                      <div key={type}>
                        <p className="text-[11px] font-bold uppercase tracking-wider text-accent-teal mt-2">{TYPE_LABEL[type]} <span className="font-normal normal-case tracking-normal text-text-muted">· {list.length}</span></p>
                        <ul className="pl-4">{list.map(a => <AssetRow key={`${a.type}/${a.id}`} asset={a} />)}</ul>
                      </div>
                    ))}
                  </div>
                </Collapsible>
              </div>
            </div>
          )}
          {!open && (
            <button type="button" onClick={() => setOpen(true)} className="mt-3 text-xs text-accent-teal hover:underline">
              Show what does the work, screenshots and {assets.length} related assets
            </button>
          )}
        </div>
      </div>
    </article>
  )
}

// ── Asset inventory ────────────────────────────────────────────────────────────

function AssetInventory() {
  const byType = useMemo(() => {
    const m = {}
    for (const a of catalog.assets) (m[a.type] ||= []).push(a)
    return m
  }, [])
  return (
    <section id="inventory" className="space-y-4 scroll-mt-24">
      <div className="flex items-center gap-3">
        <h2 className="text-base font-bold uppercase tracking-widest text-text-primary">Asset Inventory</h2>
        <div className="flex-1 h-px bg-line" />
        <span className="text-xs text-text-muted">Readiness Pack {catalog.pack_version} · {catalog.assets.length} assets</span>
      </div>
      <p className="text-sm text-text-muted leading-relaxed">
        Every asset the pack installs, generated from the pack source tree. <span className="text-accent-purple">Package</span> assets
        install from the Fleet package; <span className="text-accent-gray">bootstrap</span> assets are applied by the pack loader
        because the package format has no folder for the type. Links open the object in the read-only demo cluster; Stack
        Management pages (templates, pipelines, transforms, policies, roles, data views) need a role with management access,
        which the demo analyst login may not have.
      </p>
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-2">
        {catalog.types.map(t => (
          <a key={t.key} href={`#type-${t.key}`} className="rounded-lg border border-line bg-ink-800 px-3 py-3 hover:border-accent-teal/60" style={{ borderStyle: 'solid' }}>
            <p className="text-xl font-semibold text-accent-teal leading-none">{t.count}</p>
            <p className="mt-1.5 text-[11px] text-text-muted leading-snug">{t.label}</p>
            <p className="mt-1 text-[10px] text-text-muted/60 leading-snug">{t.delivery}</p>
          </a>
        ))}
      </div>
      <p className="text-[11px] text-text-muted/70 leading-relaxed">
        The eight ML jobs are the pack's own. The demo cluster also carries seven Security-app anomaly jobs installed under the
        pack prefix (the Entity Store authentication, host and process jobs) that the eight AppB ML rules run on; they belong
        to the Security integration, not the pack.
      </p>
      <div className="space-y-2">
        {catalog.types.map(t => (
          <div key={t.key} id={`type-${t.key}`} className="scroll-mt-24">
            <Collapsible
              summary={t.label}
              count={t.count}
              note={t.stack_management ? 'Stack Management · management role needed' : null}
            >
              <div className="flex items-center justify-end mb-1">
                <LiveLink path={t.list_path} label={`All ${t.label.toLowerCase()} in the demo`} small />
              </div>
              <ul className="pl-4">{(byType[t.key] || []).map(a => <AssetRow key={a.id} asset={a} />)}</ul>
            </Collapsible>
          </div>
        ))}
      </div>
    </section>
  )
}

// ── Page ───────────────────────────────────────────────────────────────────────

export default function Capabilities() {
  const [modal, setModal] = useState(null) // { shots, index }
  const openShot = (shots, index) => setModal({ shots, index })
  const step = (d) => setModal(m => m && { ...m, index: (m.index + d + m.shots.length) % m.shots.length })

  return (
    <main className="mx-auto max-w-5xl px-8 py-10 space-y-10">
      <header>
        <h1 className="text-3xl font-semibold text-text-primary">
          M-26-14 Readiness Pack capabilities
        </h1>
        <p className="mt-4 text-base text-text-muted leading-relaxed">
          What the Readiness Pack does once it is installed, capability by capability, with the shipped assets that do the work
          and a link to each one in the read-only demo cluster. Screenshots are captured from that cluster; click one to enlarge.
          For a guided tour of the same cluster, use the{' '}
          <Link to="/demo-guide" className="text-accent-teal hover:underline">self-guided walkthrough</Link>.
        </p>
        <p className="mt-3 text-sm text-text-muted leading-relaxed">
          The Readiness Pack installs from its release package plus a bootstrap loader; ask your Elastic account team for the
          current release. The full <a href="#inventory" className="text-accent-teal hover:underline">asset inventory</a> is at the bottom of this page.
        </p>
      </header>

      <section className="space-y-5">
        <div className="flex items-center gap-3">
          <h2 className="text-base font-bold uppercase tracking-widest text-text-primary">Capabilities</h2>
          <div className="flex-1 h-px bg-line" />
          <span className="text-xs text-text-muted">{CAPABILITIES.length} capabilities · Readiness Pack {catalog.pack_version}</span>
        </div>
        {CAPABILITIES.map(cap => (
          <CapabilityArticle key={cap.id} cap={cap} onOpenShot={openShot} />
        ))}
      </section>

      <AssetInventory />

      {modal && (
        <ShotModal shots={modal.shots} index={modal.index} onClose={() => setModal(null)} onStep={step} />
      )}
    </main>
  )
}
